# /etc/asound.conf — managed by Spotifoni
# Switched via web UI: "headphone" or "i2s"

pcm.!default {
    type softvol
    slave.pcm "hw:sndrpihifiberry"
    control {
        name "Master"
        card sndrpihifiberry
    }

}

ctl.!default {
    type hw
    card sndrpihifiberry
}
