# /etc/raspotify/conf — managed by Spotifoni setup

LIBRESPOT_NAME="Marconi 378"
LIBRESPOT_BITRATE="320"
LIBRESPOT_BACKEND="alsa"
LIBRESPOT_DEVICE="default"
LIBRESPOT_INITIAL_VOLUME="50"
LIBRESPOT_VOLUME_CTRL="linear"
LIBRESPOT_ENABLE_VOLUME_NORMALISATION=""
